name: dryrun action exp
on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:
  dryrun:
    name: dryrun
    runs-on: ubuntu-latest
    steps:
      - name: Detect OS Architecture
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: jordan-dr/dr-action-exp@main
        with:
          goos: 'linux'
          goarch: 'amd64'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
